table 'Apocolypse Sales'
	lineageTag: f2a90bdb-ff7a-4328-8252-2aa0be207b4f

	column 'Cust ID'
		dataType: int64
		formatString: 0
		lineageTag: af9b5024-3df7-42c5-b6fe-e23d73d4cb22
		summarizeBy: count
		sourceColumn: Cust ID

		annotation SummarizationSetBy = Automatic

	column Customer
		dataType: string
		lineageTag: 8d5a9e34-7455-488e-b508-61d350c2a69c
		summarizeBy: none
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: int64
		formatString: 0
		lineageTag: e4bf2fcd-73ac-46a9-bc60-e74b5fba00b3
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: int64
		formatString: 0
		lineageTag: c15abc01-2a5b-4277-b17d-8ef9d3dc982f
		summarizeBy: count
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: int64
		formatString: 0
		lineageTag: e8cff48c-ca73-4e01-a281-86a46c1b2ec5
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

	column 'Date Purchased'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 62dedc0e-66c1-4650-9ece-b3771adac0be
		summarizeBy: none
		sourceColumn: Date Purchased

		variation Variation
			isDefault
			relationship: d37bfd9d-fb89-4985-8f5d-01b36cde0ad3
			defaultHierarchy: LocalDateTable_8bf430f4-36b2-4ca9-90b8-e6f3236c2dae.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'Apocolypse Sales' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\never\OneDrive\Desktop\Multi_Table_Relationship_with_all_viualisation_dashboard\Apocolypse Food Prep - Visualizations Tutorial.xlsx"), null, true),
				    #"Apocolypse Sales_Sheet" = Source{[Item="Apocolypse Sales",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Apocolypse Sales_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Cust ID", Int64.Type}, {"Customer", type text}, {"Product ID", Int64.Type}, {"Order ID", Int64.Type}, {"Units Sold", Int64.Type}, {"Date Purchased", type date}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

